config/routes.rb
Tasks::Application.routes.draw do
  resources :categories

  devise_for :users

  match "tasks/archive" => "tasks#archive", :as => :archive_task
  resources :tasks do
    member do
      get 'reopen'
      get 'close'
      get 'hold'
    end
  end

  root :to => 'tasks#index'

end

app/models/task.rb
include ActionView::Helpers::DateHelper
require 'time_diff'

class Task < ActiveRecord::Base
  belongs_to :user
  belongs_to :category

  attr_accessible :description, :status, :title, :user_id, :category_id

  validates_presence_of :title, :description

  after_create :set_task_open

  def set_task_open
    self.update_attributes :status => :open
  end

  def is_open?
    self.status == 'open' ? true : false
  end

  def is_closed?
    self.status == 'closed' ? true : false
  end

  def is_hold?
    self.status == 'hold' ? true : false
  end

  def time_spent_in_words
    distance_of_time_in_words self.date_of_completion, self.start_date, :true
  end

  def diff_between_not_to_date_of_completion
    if self.is_closed?
      Time.diff(Time.now, self.date_of_completion)[:day]
    else
      0
    end
  end
end

app/controllers/tasks_controller.rb
# encoding: UTF-8

class TasksController < ApplicationController
  before_filter :authenticate_user!

  # GET /tasks
  # GET /tasks.json
  def index
    if params[:category]
      params[:category] == 'clear' ? session[:category_selected] = nil : session[:category_selected] = params[:category]
    end

    @category_selected = session[:category_selected]

    unless @category_selected
      @tasks = Task.where("user_id = ?", current_user.id).all
    else
      if @category_selected == "none"
        @tasks = Task.where("user_id = ? AND category_id IS NULL", current_user.id).all
      else
        @tasks = Task.where("user_id = ? AND category_id = ?", current_user.id,@category_selected).all
      end
    end

    @expand_id = session[:expand_id]

    @temp = Array.new
    @tasks.each do |task|
      if task.is_closed?
        if task.diff_between_not_to_date_of_completion < 1
          @temp.push task
        end
      else
        @temp.push task
      end
    end
    @tasks = @temp

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    session[:expand_id] = @task.id

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path, :notice => 'A tarefa foi criada com sucesso.' }
        format.json { render :json => @task, :status => :created, :location => @task }
      else
        format.html { render :action => "new" }
        format.json { render :json => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    session[:expand_id] = @task.id

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to tasks_path, :notice => 'A tarefa foi atualizada com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, :notice => 'A tarefa foi removida com sucesso.' }
      format.json { head :no_content }
    end
  end

  def reopen
    @task = Task.find(params[:id])
    @task.status = "open"

    session[:expand_id] = @task.id

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path, :notice => 'A tarefa selecionada foi reaberta.' }
        format.json { head :no_content }
      else
        format.html { redirect_to tasks_path, :notice => 'A tarefa selecionada não foi reaberta.' }
        format.json { render :json => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  def close
    @task = Task.find(params[:id])
    @task.date_of_completion = DateTime.now
    @task.status = "closed"

    session[:expand_id] = @task.id

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path, :notice => 'A tarefa selecionada foi finalizada.' }
        format.json { head :no_content }
      else
        format.html { redirect_to tasks_path, :notice => 'A tarefa selecionada não foi finalizada.' }
        format.json { render :json => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  def hold
    @task = Task.find(params[:id])
    @task.start_date = DateTime.now
    @task.status = "hold"

    session[:expand_id] = @task.id

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path, :notice => 'A tarefa selecionada foi posta em execução.' }
        format.json { head :no_content }
      else
        format.html { redirect_to tasks_path, :notice => 'A tarefa selecionada não foi posta em execução.' }
        format.json { render :json => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # GET /tasks
  # GET /tasks.json
  def archive
    @tasks = Task.where("user_id = ? AND status = 'closed'", current_user.id).all
    @expand_id = session[:expand_id]

    @temp = Array.new
    @tasks.each do |task|
      if task.diff_between_not_to_date_of_completion >= 1
        @temp.push task
      end
    end
    @tasks = @temp

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @tasks }
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for(@task, :html => {:class => "well form-vertical"}) do |f| %>
    <% if @task.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@task.errors.count, "erro") %> encontrado(s):</h2>

        <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="control-group">
      <%= f.label 'Título', :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :title, :class => "span5 required" %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label 'Descrição da Tarefa', :class => "control-label" %>
      <div class="controls">
        <%= f.text_area :description, :class => "span5 required", :rows => 3 %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label 'Categoria', :class => "control-label" %>
      <div class="controls">
        <%= f.select(:category_id , Category.where("user_id = ?", current_user.id).order(:title).map { |category| [category.title.upcase, category.id] }, { :include_blank => true }) %>
      </div>
    </div>

    <%= f.hidden_field :user_id, :value => current_user.id %>

    <%= f.submit "Salvar", :class => "btn btn-primary" %>
    <%= link_to "Cancelar", :back, :class => "btn" %>

<% end %>

<script type="text/javascript">
  $(document).ready(function(){
   
   $('#new_task').validate(
   {
    rules: {
      "task[title]": {
        minlength: 5,
        required: true
      },
      "task[description]": {
        minlength: 10,
        required: true
      }
    }, 
    highlight: function(label) {
      $(label).closest('.control-group').addClass('error');
    },
    success: function(label) {
      label
        .text('OK!').addClass('valid')
        .closest('.control-group').addClass('success');
    }
   });

  });
</script>

app/views/tasks/archive.html.erb
<ul class="breadcrumb">
  <li>
    <a href="/">Início</a> <span class="divider">/</span>
  </li>
  <li class="active">Tarefas</li>
</ul>

<% i = 1 %>
<div class="accordion" id="accordion2">
  <% @tasks.each do |task| %>
    <div class="accordion-group">
      <div class="accordion-heading">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse<%= task.id %>">
          <% if task.is_closed? %>
            <strike><%= i.to_s + ". " + task.title.upcase %></strike>
          <% else %>
            <%= i.to_s + ". " + task.title.upcase %>
          <% end %>
          <%= raw '<span class="label">Aberto</span>' if task.is_open? %>
          <%= raw '<span class="label label-success">Concluído</span>' if task.is_closed? %>
          <%= raw '<span class="label label-warning">Em execução</span>' if task.is_hold? %>
        </a>
      </div>
      <div id="collapse<%= task.id %>" class="accordion-body collapse">
        <div class="accordion-inner">
          <% if task.is_hold? %>
            <div style="font-size: 80%">Iniciada em: <%= task.start_date.to_s_br %></div>
          <% end %>
         <% if task.is_closed?  %>
            <div style="font-size: 80%">Iniciada em: <%= task.start_date.to_s_br %></div>
            <div style="font-size: 80%">Finalizada em: <%= task.date_of_completion.to_s_br %> (<%= task.time_spent_in_words %>) </div>
            <p><%= task.diff_between_not_to_date_of_completion %></p>
          <% end %>
          
          <div id="task_description" class="well">
            <%= task.description %>
          </div>

          <div class="btn-group">
            <%= link_to 'Pegar', hold_task_path(task), :class => "btn btn-warning" if task.is_open? %>
            <%= link_to 'Concluir', close_task_path(task), :class => "btn btn-success", :data => { :confirm => 'Confirma conclusão da tarefa?' } if task.is_hold? %>
            <%= link_to 'Reabrir', reopen_task_path(task), :class => "btn", :data => { :confirm => 'Confirma reabertura da tarefa?' } if task.is_closed? %>
            <%= link_to 'Editar', edit_task_path(task), :class => "btn" %>
            <%= link_to 'Apagar', task, :method => :delete, :data => { :confirm => 'Tem certeza?' }, :class => "btn" %>
          </div>

        </div>
      </div>
    </div>
    <% i += 1 %>
  <% end %>
</div> 

app/views/tasks/edit.html.erb
<ul class="breadcrumb">
  <li>
    <a href="/">Início</a> <span class="divider">/</span>
  </li>
  <li class="active">Editar Tarefa</li>
</ul>

<%= render 'form' %>

app/views/tasks/index.html.erb
<ul class="breadcrumb">
  <li>
    <a href="/">Início</a> <span class="divider">/</span>
  </li>
  <li class="active">Tarefas</li>
</ul>

<div id="categories_filter">
  Filtrar Categoria: <br />
  <span id="category_link_all" class="category_link label"><%= link_to "\#TODAS", tasks_path + "?category=clear" %></span>
  <span id="category_link_none"class="category_link label"><%= link_to "\#SEM CATEGORIA", tasks_path + "?category=none" %></span>
  <% Category.all.each do |category| %>
    <span id="category_link_<%= category.id %>" class="category_link label"><%= link_to "#" + category.title.upcase, tasks_path + "?category=#{category.id}" %></span>
  <% end %>
</div>

<% i = 1 %>
<div class="accordion" id="accordion2">
  <% @tasks.each do |task| %>
    <div class="accordion-group">
      <div class="accordion-heading">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse<%= task.id %>">
          <% if task.is_closed? %>
            <strike><%= i.to_s + ". " + task.title.upcase %></strike>
          <% else %>
            <%= i.to_s + ". " + task.title.upcase %>
          <% end %>
          <%= raw '<span class="label">Aberto</span>' if task.is_open? %>
          <%= raw '<span class="label label-success">Concluído</span>' if task.is_closed? %>
          <%= raw '<span class="label label-warning">Em execução</span>' if task.is_hold? %>
        </a>
      </div>
      <% 
        expand_this = false
        if @expand_id
          if @expand_id == task.id
            expand_this = true
          end
        else
          if i == 1
            expand_this = true
          end
        end
      %>
      <div id="collapse<%= task.id %>" class="accordion-body collapse <%= raw "in" if expand_this %>">
        <div class="accordion-inner">
          <% if task.category %>
            <div style="font-size: 80%">Categoria: <%= task.category.title.upcase %></div>
          <% end %>
          <% if task.is_hold? %>
            <div style="font-size: 80%">Iniciada em: <%= task.start_date.to_s_br %></div>
          <% end %>
         <% if task.is_closed?  %>
            <div style="font-size: 80%">Iniciada em: <%= task.start_date.to_s_br %></div>
            <div style="font-size: 80%">Finalizada em: <%= task.date_of_completion.to_s_br %> (<%= task.time_spent_in_words %>) </div>
          <% end %>
          
          <div id="task_description" class="well">
            <%= task.description %>
          </div>

          <div class="btn-group">
            <%= link_to 'Pegar', hold_task_path(task), :class => "btn btn-warning" if task.is_open? %>
            <%= link_to 'Concluir', close_task_path(task), :class => "btn btn-success", :data => { :confirm => 'Confirma conclusão da tarefa?' } if task.is_hold? %>
            <%= link_to 'Reabrir', reopen_task_path(task), :class => "btn", :data => { :confirm => 'Confirma reabertura da tarefa?' } if task.is_closed? %>
            <%= link_to 'Editar', edit_task_path(task), :class => "btn" %>
            <%= link_to 'Apagar', task, :method => :delete, :data => { :confirm => 'Tem certeza?' }, :class => "btn" %>
          </div>

        </div>
      </div>
    </div>
    <% i += 1 %>
  <% end %>
</div> 

<script type="text/javascript">
  $(document).ready(function(){
    <% unless @category_selected %>
      $('#category_link_all').addClass('label-info').addClass('category_selected_link');
    <% else %>
      <% if @category_selected == "none" %>
        $('#category_link_none').addClass('label-info').addClass('category_selected_link');
      <% else %>
        $('#category_link_<%= @category_selected %>').addClass('label-info').addClass('category_selected_link');
      <% end %>
    <% end %>
  });
</script>

app/views/tasks/new.html.erb
<ul class="breadcrumb">
  <li>
    <a href="/">Início</a> <span class="divider">/</span>
  </li>
  <li class="active">Nova Tarefa</li>
</ul>

<%= render 'form' %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @task.title %>
</p>

<p>
  <b>Status:</b>
  <%= @task.status %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>