config/routes.rb
Tasks::Application.routes.draw do
  resources :categories

  devise_for :users

  match "tasks/archive" => "tasks#archive", :as => :archive_task
  resources :tasks do
    member do
      get 'reopen'
      get 'close'
      get 'hold'
    end
  end

  root :to => 'tasks#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :tasks
  belongs_to :user

  attr_accessible :title, :user_id
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, :notice => 'A categoria foi criada com sucesso.' }
        format.json { render :json => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.json { render :json => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to categories_path, :notice => 'A categoria foi atualizada com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_path, :notice => 'A categoria foi removida com sucesso.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category, :html => {:class => "well form-vertical"}) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="control-group">
      <%= f.label 'Título', :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :title, :class => "span5 required" %>
      </div>
    </div>

    <%= f.hidden_field :user_id, :value => current_user.id %>

  <div class="actions">
    <%= f.submit "Salvar", :class => "btn" %>
  </div>
<% end %>

<script type="text/javascript">
  $(document).ready(function(){
   
   $('#new_category').validate(
   {
    rules: {
      "category[title]": {
        minlength: 5,
        required: true
      }
    }, 
    highlight: function(label) {
      $(label).closest('.control-group').addClass('error');
    },
    success: function(label) {
      label
        .text('OK!').addClass('valid')
        .closest('.control-group').addClass('success');
    }
   });

  });
</script>

app/views/categories/edit.html.erb
<ul class="breadcrumb">
  <li>
    <a href="/categories">Categorias</a> <span class="divider">/</span>
  </li>
  <li class="active">Editar Categoria</li>
</ul>

<%= render 'form' %>

app/views/categories/index.html.erb
<ul class="breadcrumb">
  <li>
    <a href="/">Início</a> <span class="divider">/</span>
  </li>
  <li class="active">Categorias</li>
</ul>

<table class="table table-striped table-condensed ">
  <tr>
    <th width="83%">Título</th>
    <th width="17%"></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.title.upcase %></td>
    <td class="table_buttons">
      <div class="btn-group">
        <%= link_to 'Editar', edit_category_path(category), :class => "btn" %>
        <%= link_to 'Apagar', category, :method => :delete, :data => { :confirm => 'Tem certeza?' }, :class => "btn" %>
      </div>
    </td>
  </tr>
<% end %>
</table>

app/views/categories/new.html.erb
<ul class="breadcrumb">
  <li>
    <a href="/categories">Categorias</a> <span class="divider">/</span>
  </li>
  <li class="active">Nova Categoria</li>
</ul>


<%= render 'form' %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @category.title %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>