config/routes.rb
Tasks::Application.routes.draw do
  resources :categories

  devise_for :users

  match "tasks/archive" => "tasks#archive", :as => :archive_task
  resources :tasks do
    member do
      get 'reopen'
      get 'close'
      get 'hold'
    end
  end

  root :to => 'tasks#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasks</title>
  <%= stylesheet_link_tag "bootstrap", "application" %>
  <%= javascript_include_tag :defaults, "bootstrap", "jquery.validate.min", "jquery_validation_messages" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="row">
    <div class="span2">
      <div class="well" style="padding: 8px 0">
        <ul class="nav nav-list">
          <li class="nav-header">
            Tarefas
          </li>
          <li><%= link_to 'Nova Tarefa', new_task_path %></li>
          <li><%= link_to 'Tarefas', "/" %></li>
          <li><%= link_to 'Arquivadas', archive_task_path %></li>
          <li class="divider"></li>
          <li class="nav-header">
            Categorias
          </li>
          <li><%= link_to 'Nova Categoria', new_category_path %></li>
          <li><%= link_to 'Categorias', categories_path %></li>
          <li class="divider"></li>
          <li><%= link_to 'Sair', destroy_user_session_path, :method => :delete %></li>
        </ul>
      </div>
    </div>
    <div class="span10">
      <% if alert %>
        <div class="alert alert-success"><%= alert %></div>
      <% end %>
      <% if notice %>
        <div class="alert alert-success"><%= notice %></div>
      <% end %>
      <%= yield %>
    </div>
  </div>
</div>


</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasks</title>
  <%= stylesheet_link_tag "bootstrap", "application" %>
  <%= javascript_include_tag :defaults, "bootstrap", "jquery.validate.min", "jquery_validation_messages" %>
  <%= csrf_meta_tags %>
  <style>
    .control-group {
      margin-bottom: 0px;
    }
  </style>
</head>
<body>

<div class="container">
  <div class="row">
    <div class="offset3 span6">
      <h1 align="center">Controle de Tarefas </h1>
      <% if notice %>
      <div class="alert alert-success"><%= notice %></div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="offset4 span4">
      <%= yield %>
    </div>
  </div>
</div>

</body>
</html>